"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const container_generic_1 = require("./container-generic");
let container = new container_generic_1.Container();
container.put('Anna');
container.put('John');
container.put('Maria');
container.put('Peter');
//container.put(1000);
container.show();
container.get();
container.get();
console.log('====================================');
container.show();
container.get();
container.get();
container.show();
console.log(typeof container.get());
